# This is a workflow to generate the documentation automatically.

name: Generate Documentation

# Controls when the action will run. Triggers the workflow on push  
# events but only for the master branch
on:
  push:
    branches:
      - master


jobs:
  # This workflow contains a single job called "build"
  generate_doc:
    # The type of runner that the job will run on
    - name: build asciidoctor action
      uses: tonynv/asciidoctor-action@v1

