# This is a workflow to generate the documentation automatically.

name: Generate Documentation

# Controls when the action will run. Triggers the workflow on push  
# events but only for the master branch
on:
  push:
    branches:
      - master
jobs:
  # This workflow contains a single job called "build"
  gen_doc:
    runs-on: ubuntu-18.04
    name: Create Documentation
    steps:
      - name: Setup Graphviz environment
        uses: kamiazya/setup-graphviz@v1

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get build container
        id: adocbuild
        uses: avattathil/asciidoctor-action@master
        with:
          program: "asciidoctor -r asciidoctor-diagram -D docs --backend=html5 -o index.html docs/index.adoc"

      - name: Print execution time
        run: echo "Time ${{ steps.adocbuild.outputs.time }}"
      
      - name: Deploy docs to ghpages
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./docs
